# https://docs.travis-ci.com/user/reference/windows
os: windows
language: shell
before_install:
  - choco install python --version=3.8
  - pip install --upgrade pip
env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
  - pip install -r requirements.txt
script:
  - bash -c echo "Hello World"
before_deploy:
  - pyinstaller "showme.spec"
deploy:
  provider: releases
  api_key: $RELEASE_TOKEN
  file_glob: true
  file: dist/*.exe
  skip_cleanup: true
  draft: true
  on:
    tags: true
  name: $TRAVIS_TAG (DRAFT)