# https://docs.travis-ci.com/user/reference/windows
# https://travis-ci.community/t/current-known-issues-please-read-this-before-posting-a-new-topic/264/10
# https://docs.travis-ci.com/user/best-practices-security
os: windows
language: shell
before_install:
  - choco install python --version=3.8
  - python -m pip install --upgrade pip
# Could not get gitbash to update env variables. Hard coding python path
env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
  # - pip install -r requirements.txt
  - pip install lxml
script:
  - bash -c echo "Hello World"
  - bash -c env
  - bash -c "where python"
  - bash -c "where pip"
  
# before_deploy:
#   - pyinstaller "showme.spec"
# deploy:
#   provider: releases
#   api_key: $RELEASE_TOKEN
#   file_glob: true
#   file: dist/*.exe
#   draft: true
#   on:
#     tags: true
#   name: $TRAVIS_TAG (DRAFT)